### ISSUE TITLE
Unable to put arrays in config.

### ISSUE THREAD

**Issue by RealRONiN** [BetterPluginsSpigot/BetterYaml#13]
Hello there,
Just started using this lib and I'm unable to put array list in there

Resource folder config:
```yaml
HeartRecipe:
  Properties:
    ItemType: "PAPER"
    Name: "Heart"
    Lore: ["TT", "PP"]
````

Template folder config:
```yaml
HeartRecipe:
  Properties:
    ItemType: {HeartRecipe.Properties.ItemType}
    Name: {HeartRecipe.Properties.Name}
    Lore: [{HeartRecipe.Properties.Lore}]
```

Plugin folder config:
```yaml
HeartRecipe:
  Properties:
    ItemType: "PAPER"
    Name: "Heart"
    Lore: [
  - "TT"
  - "PP"
]
```

This is the error:

```
org.bukkit.configuration.InvalidConfigurationException: while parsing a flow node
 in 'reader', line 13, column 3:
      - "TT"
      ^
expected the node content, but found '-'
 in 'reader', line 13, column 3:
      - "TT"
      ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:304) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at in.arcadelabs.libs.BetterYaml.<init>(BetterYaml.java:284) ~[LifeSteal-1.0-SNAPSHOT.jar:?]
        at in.arcadelabs.libs.BetterYaml.<init>(BetterYaml.java:88) ~[LifeSteal-1.0-SNAPSHOT.jar:?]
        at in.arcadelabs.libs.OptionalBetterYaml.<init>(OptionalBetterYaml.java:92) ~[LifeSteal-1.0-SNAPSHOT.jar:?]
        at in.arcadelabs.libs.OptionalBetterYaml.<init>(OptionalBetterYaml.java:72) ~[LifeSteal-1.0-SNAPSHOT.jar:?]
        at in.arcadelabs.lifesteal.utils.ConfigUtils.loadFiles(ConfigUtils.java:18) ~[LifeSteal-1.0-SNAPSHOT.jar:?]
        at in.arcadelabs.lifesteal.hooks.LifeStealHook.init(LifeStealHook.java:97) ~[LifeSteal-1.0-SNAPSHOT.jar:?]
        at in.arcadelabs.lifesteal.LifeSteal.onEnable(LifeSteal.java:41) ~[LifeSteal-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:1019) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at org.bukkit.Bukkit.reload(Bukkit.java:909) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:549) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:523) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a flow node
 in 'reader', line 13, column 3:
      - "TT"
      ^
expected the node content, but found '-'
 in 'reader', line 13, column 3:
      - "TT"
      ^

        at org.yaml.snakeyaml.parser.ParserImpl.parseNode(ParserImpl.java:510) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.parseFlowNode(ParserImpl.java:400) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.access$2600(ParserImpl.java:121) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceEntry.produce(ParserImpl.java:771) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceFirstEntry.produce(ParserImpl.java:732) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:156) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:240) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:186) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-1.30.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:102) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 27 more
[20:27:54 ERROR]: Cannot load plugins\LifeSteal\config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a flow node
 in 'reader', line 13, column 3:
      - "TT"
      ^
expected the node content, but found '-'
 in 'reader', line 13, column 3:
      - "TT"
      ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:304) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:158) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:134) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at in.arcadelabs.libs.aikar.acf.BukkitCommandManager.<init>(BukkitCommandManager.java:136) ~[ArcadeLibs.jar:?]
        at in.arcadelabs.libs.aikar.acf.PaperCommandManager.<init>(PaperCommandManager.java:35) ~[ArcadeLibs.jar:?]
        at in.arcadelabs.lifesteal.hooks.LifeStealHook.registerCommands(LifeStealHook.java:69) ~[LifeSteal-1.0-SNAPSHOT.jar:?]
        at in.arcadelabs.lifesteal.hooks.LifeStealHook.init(LifeStealHook.java:99) ~[LifeSteal-1.0-SNAPSHOT.jar:?]
        at in.arcadelabs.lifesteal.LifeSteal.onEnable(LifeSteal.java:41) ~[LifeSteal-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:1019) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at org.bukkit.Bukkit.reload(Bukkit.java:909) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:549) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:523) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1623]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a flow node
 in 'reader', line 13, column 3:
      - "TT"
      ^
expected the node content, but found '-'
 in 'reader', line 13, column 3:
      - "TT"
      ^

        at org.yaml.snakeyaml.parser.ParserImpl.parseNode(ParserImpl.java:510) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.parseFlowNode(ParserImpl.java:400) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.access$2600(ParserImpl.java:121) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceEntry.produce(ParserImpl.java:771) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceFirstEntry.produce(ParserImpl.java:732) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:156) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:240) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:186) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-1.30.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:102) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 27 more
```

**Comment by Nuytemans-Dieter** [comment]
Hello there, thank you for reporting an issue! 
While lists are not supported at this time, it would be a very nice addition. For now, I won't be able to add this feature but I would accept any PR that adds support
